<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/question-type-multiple-correct.png">
			<?php echo $this->translate('Categories');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $this->cancel_url;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
	<div class="clear"></div>

	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Title');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a title');?>" value="<?php echo $this->title;?>" class="inputbox required" name="title" />
        			&nbsp;&nbsp; <img title="<?php echo $this->translate('Page Title');?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Status');?>:</td>
				<td>
					<select name="status" class="select">
						<?php if($this->status) { ?>
						<option selected="selected" value="1"><?php echo $this->translate('Active');?></option>
						<option value="0"><?php echo $this->translate('Inactive');?></option>
						<?php } else { ?>
						<option value="1"><?php echo $this->translate('Active');?></option>
						<option selected="selected" value="0"><?php echo $this->translate('Inactive');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Meta title');?>:</td>
				<td>
					<input type="text" size="55" value="<?php echo $this->meta_title;?>" class="inputbox" name="meta_title" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Meta description');?>:</td>
				<td>
					<textarea rows="4" cols="53" name="meta_description" class="valid"><?php echo $this->meta_description;?></textarea>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Meta keywords');?>:</td>
				<td>
					<textarea rows="4" cols="53" name="meta_keywords" class="valid"><?php echo $this->meta_keywords;?></textarea>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('SEO query');?>: </td>
				<td>
					<input type="text" size="55" value="<?php echo $this->keyword;?>" class="inputbox" name="keyword" />
	        		&nbsp;&nbsp; <img title="<?php echo $this->translate('Link to be used for navigation');?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
	        	</td>
			</tr>
					
			<tr>
				<td><?php echo $this->translate('Image');?>:</td>
				<td>
					<input type="hidden" name="image" value="<?php echo $this->image; ?>" id="site_favicon" />
					<img id="preview_favicon" src="<?php echo $this->preview_image;?>" />
					<br />
					<a style="cursor: pointer;" onclick="image_upload('site_favicon', 'preview_favicon');"><?php echo $this->translate('Browse Files'); ?></a>
					&nbsp;&nbsp;|&nbsp;&nbsp;
					<a style="cursor: pointer;" onclick="$('#preview_favicon').attr('src', '<?php echo $this->preview_image; ?>'); $('#site_favicon').attr('value', '');"><?php echo $this->translate('Clear Image'); ?></a>
				</td>
			</tr>
					
		</tbody>
	</table>
	
	
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $this->cancel_url;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
</form>