<meta name="title" content="<?php echo $this->user['title'];?>" />
<meta name="description" content="<?php echo $this->user['description'];?>" />

<meta name="medium" content="image"/>
<meta http-equiv="imagetoolbar" content="no"/>

<link rel="image_src" href="<?php echo $this->user['avatars']['avatar_image_b'];?>"/>
<link rel="canonical" href="<?php echo $this->user['user_url'];?>"/>

<link rel="alternate" type="application/rss+xml" title="<?php echo $this->user['user_feed_title'];?>" href="<?php echo $this->user['user_feed_url'];?>" />