<div id="error-body">
	<p class="icon"><a href="./"><img src="data/images/error_Downtime_icon.png" alt="" /></a></p>
	<div class="textbox">
		<h1><?php echo $this->translate('Sorry!');?></h1>
		<p><?php echo $this->translate('Sorry, there was impossible to login with your instagram account.');?></p>
		<?php if($this->page_login_trouble) { ?>
		<p>
			<?php echo $this->translate('Having trouble?');?> <a href="<?php echo $this->page_login_trouble['href'];?>"><?php echo $this->translate('Read more here.');?></a>
		</p>
		<?php } ?>
	</div>
</div>