<div id="error-body">
	<p class="icon"><a href="./"><img src="data/images/error_Downtime_icon.png" alt="" /></a></p>
	<div class="textbox">
		<h1><?php echo $this->translate('Sorry!');?></h1>
		<p> <?php echo $this->translate('Sorry, your Twitter account is not associated with any Pintastic account.');?></p>
		<p><?php echo $this->translate('If you have a Pintastic account, try logging in with your email and password. Or, please request an invite to create an account.');?></p>
		<?php if($this->page_login_trouble) { ?>
		<p>
			<?php echo $this->translate('Having trouble?');?> <a href="<?php echo $this->page_login_trouble['href'];?>"><?php echo $this->translate('Read more here.');?></a>
		</p>
		<?php } ?>
	</div>
</div>