<?php echo $this->header_part; ?>

<div id="formcontainerwrapper">
	<div id="formcontainer">
		<form method="post" action="" class="main-form">
			<h3 class="title-9"><?php echo $this->translate('Change Password');?></h3>
			<div class="row">
				<div class="cell-left">
					<label for="id_old_password"><?php echo $this->translate('Old');?></label>
				</div>
				<div class="cell-center">
					<input type="password" id="id_old_password" name="old_password" />
				</div>
				<div class="cell-right">
					<p class="helptext"><?php echo $this->translate('Your current password'); ?> - <a href="<?php echo $this->reset;?>"><strong><?php echo $this->translate('Don\'t know your password?');?></strong></a></p>	
				</div>
				<div class="clear"></div>
			</div>
			<div class="row">
				<div class="cell-left">
					<label for="id_new_password1"><?php echo $this->translate('New');?></label>
				</div>
				<div class="cell-center">
					<input type="password" id="id_new_password1" name="new_password1" />
				</div>
				<div class="cell-right">
					<p class="helptext"><?php echo $this->translate('Be tricky!'); ?></a></p>	
				</div>
				<div class="clear"></div>
			</div>
			<div class="row">
				<div class="cell-left">
					<label for="id_new_password2"><?php echo $this->translate('New, Again');?></label>
				</div>
				<div class="cell-center">
					<input type="password" id="id_new_password2" name="new_password2" />
				</div>
				<div class="cell-right">
					<p class="helptext"><?php echo $this->translate('Confirm password');?></a></p>	
				</div>
				<div class="clear"></div>
			</div>
			<div class="submit"><button type="submit" class="red-button big-button"><?php echo $this->translate('Change Password');?></button></div>
		</form>
	</div>
</div>

<?php if($this->error) { ?>
<script type="text/javascript">
head.ready('main',function(){
	Pins.error('<?php echo $this->error;?>');
});
</script>
<?php } ?>

<?php echo $this->footer_part; ?>