<div id="formcontainer">
	<div class="popup">
		<form class="main-form event-price-holder" action="<?php echo $this->from_url;?>" method="post">
			<div class="row">
				<div class="cell-center">
					<div class="pin-info">
						<div class="thumb">
							<p class="ribbon-price">
								<strong class="price event-price-html-display"></strong>
							</p>
							<?php if(!$this->pin_gallery) { ?>
							<p class="thumbshadow">
								<img src="data/images/ajax-loader.gif" data-original="<?php echo $this->images['thumb_image_b'];?>" alt="" class="event-load-lazy-load" />
							</p>
							<?php } else { ?>
							<div class="drag-sort">
								<ul class="event-drag-sort">
								<?php foreach($this->pin_gallery AS $key => $image) { ?>
								<li class="media media_<?php echo $key;?>"> 
									<img class="event-load-lazy-load" src="data/images/ajax-loader.gif" data-original="<?php echo $image['thumb_image_a'];?>" alt="" /> 
									<input type="hidden" value="<?php echo $image['thumb_original_a'];?>" name="gallery[]" />
								</li>
								<?php } ?>
								</ul>
								<div class="clear"></div>
							</div>
							<?php } ?>
						</div>
						<div class="data">
							<select name="board_id" class="event-board-style">
								<?php foreach($this->boards AS $board) { ?>
								<option value="<?php echo $board['board_id'];?>"><?php echo $board['title'];?></option>
								<?php } ?>
							</select>
							<textarea class="event-price-textarea" name="description" id="message" rows="5" cols="30"><?php echo $this->description;?></textarea>
						
							<?php if($this->form_extensions) { ?>
							<div class="extensions">
								<?php foreach($this->form_extensions AS $extension) { ?>
								<?php echo $extension['html'];?>
								<?php } ?>
							</div>
							<?php } ?>
						
						</div>
						<div class="clear"></div>
					</div>
				</div>
				<div class="cell-right">
					<p class="helptext helptext-padT">
						<span class="text_counter"></span>
					</p>
				</div>
				<div class="clear"></div>
			</div>
			<div class="submit"><button class="red-button big-button event-click-submit-disable"><?php echo $this->translate('Pinit');?></button></div>
			<p class="hide">
				<input type="hidden" name="price" value="<?php echo $this->price;?>" class="event-price-input-holder">
				<?php if(!$this->pin_gallery) { ?>
				<input type="hidden" name="media" value="<?php echo $this->images['thumb_original_b'];?>">
				<?php } ?>
				<input type="hidden" name="title" value="<?php echo $this->title;?>">
				<input type="hidden" name="from" value="<?php echo $this->from;?>">
				<input type="hidden" name="is_video" value="<?php echo $this->is_video;?>">
				<input type="hidden" name="via" value="<?php echo $this->via;?>">
				<input type="hidden" name="repin_from" value="<?php echo $this->pin_id;?>">
				<input type="hidden" name="from_repin" value="<?php echo $this->from_repin;?>">
				<input type="hidden" name="price" class="event-price-input-holder" value="<?php echo $this->formated_price;?>" />
			</p>
		</form>
	</div>
</div>


<?php $key = str_replace('.','',microtime(true));?>
<script type="text/javascript">
$(document).ready(function(){

	$('.event-price-textarea').priceExpresion({
		expresions: pintastic_config.regExPrice,
		callback: function() {
			if($.trim(this.val())) {
				$('.event-click-submit-disable').removeClass('disabled').attr('disabled', false);
			} else {
				$('.event-click-submit-disable').addClass('disabled').attr('disabled', true);
			}
		}
	}).jqEasyCounter({
		holder: '.text_counter',
		maxChars: 500,
		maxCharsWarning: 470,
		template: '<?php echo $this->translate('{count} characters remaining');?>'
	});

	Pins.initSelectBoxCreateBoard('.event-board-style');

	$('.popup form').unbind('submit').submit(function(){
		var button = $('.event-click-submit-disable').addClass('disabled').attr('disabled', true);
		loading.load(button);
		$.post('<?php echo $this->from_url;?>', $(this).serialize(), function(result){
			if(result.error) {
				Pins.error(result.error);
			} else if(result.pin_url) {
				if(pintastic_config.disable_js) {
					window.location = result.pin_url;
				} else {
					if(pintastic_config.disable_js) {
						window.location = result.pin_url;
					} else {
						Pins.openDetailBox();
						var link = $('<a>').attr('href', result.pin_url).addClass('event-click-open-detail-view');
						link.appendTo('body').click().remove();
						if(result.repin_from && result.stats) {
							for(i in result.stats) {
								$('#'+result.repin_from+' .stats .' + i).html(result.stats[i]);
							}
						}
					}
				}
			} else if(result.location) {
				window.location = result.location;
			} else {
				Pins.error(result);
			}
			loading.stop();
		}, 'json');
		return false;
	});

	Pins.lazyLoad('.event-load-lazy-load');

	<?php if($this->pin_gallery) { ?>
	$(".event-drag-sort").dragsort({ itemSelector: ".media",dragSelector: ".media", placeHolderTemplate: "<"+"li class='media'><"+"/li>" });
	<?php } ?>
	
});


</script>