<?php if($this->redirect) { ?>
<script type="text/javascript">
window.location = '<?php echo $this->redirect;?>';
</script>
<h2><?php echo $this->translate('Redirect to login!');?></h2>
<?php } else { ?>
<?php if($this->error_upload_image) { ?>
<script type="text/javascript">
$(document).ready(function(){
	Pins.notify('<?php echo $this->translate('We couldn\'t find any images');?>');
});
</script>
<?php } ?>

<div class="popup">
	<div class="main-form noform">
		<div id="uploader"><?php echo $this->translate('You browser doesn\'t have HTML 4 support.');?></div> 
		<div class="submit nlp">
			<a class="red-button disabled big-button event-click-steptwo" href="<?php echo $this->steptwo;?>" title="<?php echo $this->translate('Gallery pin');?>"><?php echo $this->translate('Next »');?></a>
		</div>
	</div>
</div>


<script type="text/javascript">
head.css('data/css/plugins/plupload.css');
head.js({'plupload':'data/js/plugins/uploader/plupload.js'},
		{'plupload_html4':'data/js/plugins/uploader/plupload.html4.js'},
		{'plupload_html5':'data/js/plugins/uploader/plupload.html5.js'},
		{'plupload_queue':'data/js/plugins/uploader/jquery.plupload.queue.js'},
		{'plupload_i18n':'<?php echo $this->js_i18n;?>'},
		function() {

			$("#uploader").pluploadQueue({
				runtimes : 'html5,html4',
				url : '<?php echo $this->upload_action;?>',
				max_file_size : '100M',
				unique_names : false,
				filters : [
					{title : "<?php echo $this->translate('Image files');?>", extensions : "jpg,jpeg,gif,png"}
				]
			});

			var uploader = $("#uploader").pluploadQueue();

			<?php if($this->files_limit) { ?>
				uploader.bind('FilesAdded', function(up, files) {
					if (uploader.files.length > <?php echo $this->files_limit;?>) {
						var removed = [];
						for( var i = 0; i < uploader.files.length; i++ ) {
							if( i >= <?php echo $this->files_limit;?>) {
								removed.push(uploader.files[i]);
							}
						}
						for(i in removed) {
							uploader.removeFile(removed[i]);
						}
						if(removed.length > 0) {
							Pins.notify(('<?php echo $this->translate('Max files upload is %s files');?>').replace('%s',<?php echo $this->files_limit;?>));
						}
			        }
				});
			<?php } ?>
			
			uploader.bind('FileUploaded', function(up, file, res) {

				try {
					var json = jQuery.parseJSON(res.response);
					if(json.error) {
						uploader.trigger("Error", {
		                    code: 100,
		                    message: json.error,
		                    file: file,
		                    status: res.status
		                });
					} else if(json.location) {
						window.location = json.location;
						return;
					}
				} catch (e) { }
				
		        if(up.total.queued == 0) {
		        	$('.event-click-steptwo').unbind('.disable-fb').addClass('event-click-open-popup').removeClass('disabled');
		        }
		        
		    });
			
		});

	$('.event-click-steptwo').bind('click.disable-fb',function() {
		return false;
	});

</script>
<?php }?>