<?php echo $this->header_part; ?>
<div class="titlebar">
	<div class="title">
		<h3 class="title-8"><?php echo $this->translate('Pins from');?> <a onclick="target='_blank'" href="http://<?php echo $this->source['source'];?>"><?php echo $this->source['source'];?></a></h3>
	</div>
</div>
<div id="boxcontainerwrapper">
	<div id="boxcontainer" class="event-masonry-container"><?php echo $this->result_data;?></div>
</div>
<?php echo $this->footer_part; ?>