<?php 
	$module = $this->getRequest()->getModule();
?>

<form action="" method="post">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/extensions.png">
			<a href="<?php echo $this->modules_url;?>"><?php echo $this->translate('Modules');?></a> >> 
			<a href="<?php echo $this->modules_storage_url;?>"><?php echo $this->translate('Storage');?></a> >> 
			<?php echo $this->translate('Amazon S3');?>
		</h3>
		
		<?php if($this->successfu_edite || $this->error) { ?>
		<?php if($this->successfu_edite) { ?>
		<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
		<?php } else if($this->error) { ?>
		<span id="fader" class="fleft mleft30"><span class="msgError"><span><?php echo $this->translate('Error!');?></span><?php echo $this->error;?></span></span>
		<?php } ?>
		<script type="text/javascript"> 
		// <![CDATA[
		$(document).ready(function() {       
			setTimeout(function() {
				$("#fader").customFadeOut("slow" ,    
				function() {       
					$("#fader").remove();  
				});
			},
			4000);
		});
		// ]]>
		</script>
		<?php } ?>
	
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $this->modules_storage_url;?>"><?php echo $this->translate('Cancel');?></a>
		</div>
		
		<div class="clear"></div>
	</div>
	
	<p class="info">
		<?php echo $this->translate('Modules >> Amazon S3 Manager');?><br>
	</p>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td><?php echo $this->translate('Aws Access Key');?>:</td>
				<td>
					<input type="text" size="55" value="<?php echo $this->amazons3_access_key;?>" class="inputbox" name="amazons3[amazons3_access_key]" />
	        	</td>
			</tr>
					
			<tr>
				<td><?php echo $this->translate('Aws Secret Key');?>:</td>
				<td>
					<input type="text" size="55" value="<?php echo $this->amazons3_secret_key;?>" class="inputbox" name="amazons3[amazons3_secret_key]" />
	        	</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Bucklet');?>:</td>
				<td>
					<input type="text" size="55" value="<?php echo $this->amazons3_bucklet;?>" class="inputbox" name="amazons3[amazons3_bucklet]" />
	        	</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Aws Bucklet Location');?>:</td>
				<td>
					<input type="text" size="55" value="<?php echo $this->amazons3_bucklet_location;?>" class="inputbox" name="amazons3[amazons3_bucklet_location]" />
	        	</td>
			</tr>
				</tbody>
		
		<tfoot>
			<tr>
				<td colspan="2">
					<div class="fright mtop3">
						<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $this->modules_storage_url;?>"><?php echo $this->translate('Cancel');?></a>
					</div>
					<div class="clear"></div>
				</td>
			</tr>
		</tfoot>
	</table>
</form>