<meta name="title" content="<?php echo $this->board['title'];?>" />
<meta name="description" content="<?php echo $this->board['description'];?>" />
<meta name="keywords" content="<?php echo $this->board['keywords'];?>" />

<meta name="medium" content="image"/>
<meta http-equiv="imagetoolbar" content="no"/>

<link rel="image_src" href="<?php echo $this->board['images']['thumb_image_b'];?>"/>
<link rel="canonical" href="<?php echo $this->board['board_url'];?>"/>

<link rel="alternate" type="application/rss+xml" title="<?php echo $this->board['board_feed_title'];?>" href="<?php echo $this->board['board_feed_url'];?>" />