<?php echo $this->header_part; ?>
<script type='text/javascript'>
	var model  = new Model;
	model.get(window.location.href,function(data){
		model.getTemplate('pinBox',function(pinBox){
			$.each(data,function(i,pin){
				if(pin.template === 'pins'){
					console.log(pin);
					pin.grayImg = model.grayImg;
					var pin = $(pinBox).tmpl(pin).appendTo("#container");
					pin.find('img').LazyLoad();
				}
			});
		});
	});
</script>

<script type="text/javascript" src='data_mobile/js/infscroll.js'>
	$(document).ready(function(){
		
		infScroll();
	});
</script>
	<div id="container">
		
	
		
		<div class="clear"></div>
	</div>

<?php echo $this->footer_part; ?>