	<!--<script type="text/javascript" src="../data/js/search.js"></script>-->
	<script type='text/javascript' src='data_mobile/js/model.js'></script>
	<script type='text/javascript' src='data/js/jquery_lib/jquery.LazyLoad.js'></script>
	
	<script>
	
		//get the logo url from the php $this obj and set is as js var
		var logoUrl = <?php echo "'".$this->site_logo."'" ?>;
		//console.log(logoUrl);
                 
		//then in the file js/animations.js we will set it as a background image of #mobile_logo
	
	</script>
	
        	<?php 
        		//check if user is loged and pass a variable 
        		$this->is_loged == 0 ? JO_Registry::set('is_loged', false) : JO_Registry::set('is_loged', true);
        
        	 ?>
        
	 <script type='text/javascript'>
		$(document).ready(function(){
			var model = new Model;
			model.upload($("#camera_btn"));
		});
	 </script>
	 <div id='wrapper'>
		<div class='header_wrapper'>
			<div id='header' style='position:fixed !important;width:99% !Important;'>
			   <div class="ir" id="logo_wrapper">
					<a href="/">
						<h1 id='mobile_logo'>
							
						</h1>
					</a>
				</div>
				   <?php if($this->is_loged !== 0): ?>
								<div class="pressable wrapper disabled" id="profile_btn" ontouchstart="">
									<img src="<?php echo $this->self_avatar['avatar_image_a'];?>" alt="Profile">
									<div class="ir" id="profile_arrow">Dropdown</div>
									<div class="overlay" style="opacity: 1;background: transparent"></div>
								</div>
					<?php endif; ?>
				<div id="outer_wrapper">
						<div id="search" class="pressable wrapper">
							<div class="ir" id="mobile_search">
								<div class="overlay"></div>
							</div>
						   
						</div>
				</div>
				<?php if(JO_Session::get('user[user_id]')) {?>
					<div class="pressable wrapper disabled" id="camera_btn" ontouchstart="">
									<div class="ir" id="camera">
										<div class="overlay"></div>
									</div>
					</div>
								
				<?php } ?>
		   </div>   
		</div>
               
                 <div class="dropdown" id="search_dropdown" style='position:fixed !important;'>
                            <div class="container">
                                <ul id="search_explore" class="contents" >
                                    <li class="search">
                                        <form action="search" method="get">
                                            <input id="query" name="q" type="text" action='/search' placeholder="<?php echo $this->translate("Search"); ?>">
                                        </form>
                                    </li>
                                    <?php if($this->is_loged !== 0): ?>
                                    	<a class="selected" href="">
                    						<li><?php echo $this->translate('Pinners You Follow') ?></li>
                						</a>
                                    <?php endif; ?>
                                    <li id='touch_arrow'>
                                    	<a id='touch_arrow_link'>
											<?php echo $this->translate('Everything') ?>
                                    	</a>
                                    	<div class='touch_arrow' id='touch_arrow'></div>
                                   	</li>
                                   	 <li>
                                    	<a href='/popular' style="padding-right: 100px">
											<?php echo $this->translate('Popular') ?>
                                    	</a>
                                   	</li>
                                   	 <li>
                                    	<a href='/gifts' style="padding-right: 100px">
											<?php echo $this->translate('Gifts') ?>
                                    	</a>
                                   	</li>
                                </ul>
                                
                                <!-- start of categories -->
                                <div id='categories'>
                                	<ul class='contents'>
                                		<a href='/all'>
                                			<li>
												<?php echo $this->translate('All') ?>
                                			</li>
                                		</a>
                                		
                                			<?php  for($i = 0; $i < count($this->categories); $i++): ?>
            
							            	<?php if($this->categories[$i]['active'] == false): ?>                    		
                              			
                              		  		<a href='<?php echo $this->categories[$i]['href']?>'>
                                				<li>
                                					<?php echo $this->translate($this->categories[$i]['title']); ?>
                                				</li>
                                			</a>
                              
                                 		
	                	            		 <?php endif; ?>
           									 
           									<?php endfor; ?>
                                	
                                	</ul>
                                </div>
                            </div>
                        </div>
                        
                        
                        <?php if($this->is_loged): ?>
                        	<div class="dropdown" id="user_dropdown" style='position:fixed !important;'>
    							<ul>
        						<a href="<?php echo $this->self_profile; ?>"><li><?php echo  $this->translate('Profile') ?></li></a>
        
       							<a href="?full_version" id="switch_to_full"><li ontouchstart=""><?php echo  $this->translate('Full Site') ?></li></a>
       							<a href="/users/logout/" id="logout_button"><li ontouchstart=""><?php echo  $this->translate('Log Out') ?></li></a>
    							</ul>
</div>
                       	<?php endif; ?>
                        
                     
                           <?php JO_Registry::get('is_login_form'); ?>
       <!-- if the user is NOT logged in -->
    
      	<?php if($this->is_loged == 0): ?> 
      	
      	 	
       <div class='banner' id='login_banner'>
       		<h2>
       			<span>
       			 <?php echo sprintf($this->translate('%s is an online pinboard.'), $this->site_name);?>
       			</span>
       			<strong>
					<?php echo $this->translate('Organize and share things you love.'); ?>
       				
       			</strong>
       		</h2>
       		
       		<div class='buttons'>
                   
       			<a class='white mbtn' id='request_invite' href='/landing'>
       				<?php if(Helper_Config::get('enable_free_registration')): ?>
                                
                                <strong><?php echo $this->translate('Sing Up'); ?></strong>
                                
                                <?php else: ?>
                                
                                 <strong><?php echo $this->translate('Request Invitation'); ?></strong>
                                
                                <?php endif; ?>
       				<span></span>
       			</a>
       			
       			<a class='red mbtn' href='/users/login'>
       				<strong><?php echo $this->translate('Login'); ?></strong>
       				<span></span>
       			</a>
       		</div>
       		
       		<div class="stitching">
            <div class="stitch"></div>
            <div class="stitch white"></div>
        </div>
       </div>
       	
       <?php endif; ?>
       <div class='pinboard home'>
       	
       	
       	
 
